### ISSUE TITLE
[BUG] Ores may not be generating

### ISSUE THREAD

**Issue by northwesttreesgaming** [Max094Reikeb/Electrona-Project#5]
**Describe the bug**
Overworld ores may not be generating.

**To Reproduce**
1. Use the fill command to replace (stone, andesite, diorite, granite, gravel, dirt, sand, and grass_block) in a effected area.
2. Look for your ores.

**Expected behavior**
Unable to locate any ores in the overworld in caves or when removing stone and other blocks.

**Screenshots**
![2021-03-23_12 53 23](https://user-images.githubusercontent.com/47284617/112209524-ccca3c00-8bd6-11eb-96b9-d4a776e50ab1.png)

**Mod informations (please complete the following information):**
 - Mod Version: a2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.0

**Additional context**
I explored a few caves and did some strip digging at the levels the Tin ore should be generating at, and I could not find any ore.
I then used the fill command to remove all vanilla blocks except for the ores and I could not find any in a single chunk, they may be really rare or not generating.

**Comment by Max094Reikeb** [comment]
How many chunks did you look in?

**Comment by northwesttreesgaming** [comment]
just that one XD
